# services:

#   db:
#     image: postgres:17

#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: task_management_db

#     ports:
#       - "5432:5432"

#   api:
#     build: .

#     ports:
#       - "8000:8000"

#     depends_on:
#       - db