"""add password reset fields

Revision ID: 35f22ff3e162
Revises: c1e43f47e67a
Create Date: 2026-08-11 11:32:48.771422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f22ff3e162'
down_revision: Union[str, Sequence[str], None] = 'c1e43f47e67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(
    "uq_users_reset_token",
    "users",
    ["reset_token"]
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "uq_users_reset_token",
    "users",
    type_="unique"
)
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
